project:
  type: website
  title: "Industry Club, Department of Computer Science, University of Manchester"
  execute-dir: project
  output-dir: docs
  render: 
      - index.qmd
      - events.qmd
      - research.qmd
      - mentoring.qmd
      - guests.qmd
      - recruitment.qmd
      - manchester.qmd
      - contact.qmd


website:
  title: "Industry Club, Department of Computer Science, University of Manchester"
  # subtitle: "stuff"
  site-url: https://industry-club.cs.manchester.ac.uk
  repo-url: https://github.com/UoMCS/iclub
  issue-url: https://github.com/UoMCS/iclub/issues/new/
  repo-actions: [edit,issue]
  navbar:
    logo: logo-university-of-manchester-allwhite.png
    logo-alt: "Quarto logo."
    background: "#660099"
    #left:
      #- href: index.qmd
      #  text: Home
      #- about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/csmcr
      - icon: github
        href: https://github.com/UoMCS/iclub
  page-footer:
    left: Part of the [School of Engineering](https://www.se.manchester.ac.uk/about/schools-and-departments/school-of-engineering/) at the [Unversity of Manchester](https://www.manchester.ac.uk)
    #center:
    #  - text: "About"
    #    href: about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/csmcr
      - icon: github
        href: https://github.com/UoMCS

  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - events.qmd
      - research.qmd
      - mentoring.qmd
      - guests.qmd
      - recruitment.qmd
      - manchester.qmd
      - contact.qmd
  page-navigation: true


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple



#date: today
#date-format: iso

# jupyter: julia-1.8
