---
title: "Contacts"
subtitle: Key industrial contacts in the Department of Computer Science
---

Phone numbers can be found on contact pages below. All emails are `...@manchester.ac.uk` 

## Professor Andrew Stewart

* Andrew serves as Head of the Department of Computer Science 
* [research.manchester.ac.uk/en/persons/andrew.j.stewart](https://research.manchester.ac.uk/en/persons/andrew.j.stewart)
* email `andrew.j.stewart@...` 

## Professor Lucas Cordeiro

* Lucas is Director of Business Engagement and Innovation for Computer Science
* [research.manchester.ac.uk/en/persons/lucas.cordeiro](https://research.manchester.ac.uk/en/persons/lucas.cordeiro)
* email `lucas.cordeiro@...`


## Dr. Suzanne Embury

* Suzanne is Research Impact Lead and a [Reader](https://en.wikipedia.org/wiki/Reader_(academic_rank)) in Software Engineering
* [research.manchester.ac.uk/en/persons/suzanne.m.embury](https://research.manchester.ac.uk/en/persons/suzanne.m.embury)
* email `suzanne.m.embury@...`

## Dr. Duncan Hull 

* Duncan is Employability Lead and a Director of Business Engagement and Innovation. He is a Senior Lecturer in the Department of Computer Science
* [research.manchester.ac.uk/en/persons/duncan.hull](https://research.manchester.ac.uk/en/persons/duncan.hull)
* email `duncan.hull@...`

## Dr. David Petrescu

* David is Placement Tutor, with pastoral responsibilty for our students while they are on placement.  He is a Lecturer in the Department of Computer Science
* [research.manchester.ac.uk/en/persons/david-petrescu](https://research.manchester.ac.uk/en/persons/david-petrescu/)
* email `david.petrescu@...`