---
title: "Hello"
bibliography: references.bib
---

Hello and welcome to the Industry Club of the Department of Computer Science at the University of Manchester. Membership of this community is open to employers who want to engage, recruit and collaborate with students and staff from the Department of Computer Science by:

* Collaborating on [research](research.html) projects
* Participating in industrially focused teaching, such as [guest lectures](guests.html), [software engineering mentoring](mentoring.html), [careers fairs](recruitment.html) and [other events](events.html)
* [Recruiting our students](recruitment.html) before and after they graduate from:
    + undergraduate Bachelors degrees
    + postgraduate degrees, both Masters and PhDs


## Employers {#employers}
Our students, staff and alumni work with a wide range of employers from local startups through to global corporations, and everything in between. According to [highfliers.co.uk](https://www.highfliers.co.uk), the University of Manchester is the most targeted University in the UK by the [Times Top 100 Graduate Employers](https://www.top100graduateemployers.com), [@highfliers2026] this is reflected in the range of organisations we collaborate with.

![The University of Manchester is the most targeted University in the UK by the Times Top 100 Graduate Employers, Table reproduced from  [@highfliers2026]](highfliers2026.png)


## Join our mailing list {#industryclub}

Employers are welcome to join our industry club mailing list by sending an email to `listserv@listserv.manchester.ac.uk` with the the text `subscribe cs-industryclub yourfirstname yoursecondname` in the body of the email message. You can do this by [subscribing here](mailto:listserv@listserv.manchester.ac.uk?subject=subscribe cs-industryclub yourfirstname yoursecondname!&body=subscribe cs-industryclub yourfirstname yoursecondname)

The mailing list is low-traffic, typically two to three updates per year with notifications of upcoming events and meetings. If you join our mailing list, we will not to spam you or sell your email details on to third parties.

 The industry club is part of our [wider business engagement activities](https://www.cs.manchester.ac.uk/connect/business-engagement/).

