---
title: "Research"
subtitle: Applied and industrial research projects
bibliography: references.bib
---

There are several different kinds of industrial and applied research projects that employers can engage with through our Bachelors, Masters, PhD students and staff.

![Students working on the SpiNNaker project, a million-core supercomputer using Spiking Neural Networks used to simulate mammalian brains [@spin] ](research.jpg)


## Co-supervised projects {#cosupervise}
If you would like to co-supervise a project student in collaboration with an academic member of staff, there are several options. The best option depends on the domain, level and duration of the project:

### Bachelors projects  {#bachelors}
Bachelors these are completed in the final year of a Bachelors degree and last for six months, starting in September and finishing in March. Projects are proposed (and offered to students) in March and start in September of the same year. For Bachelors projects, speak to the third year projects manager: Terence Morley see [project contacts](contact.html#cosupervise)


### Masters projects {#masters}
At any given time, we have around 250 Masters students. Masters projects are six months in duration but start in March and finish in September every year. Projects are proposed (and offered to students) in the preceding November. For Masters projects, speak to the Postgraduate taught programme director: Sarah Clinch see [project contacts](contact.html#cosupervise)



### PhD projects {#phd}

We have around 250 PhD students at any given time.  For industrially sponsored or co-supervised projects, contact our postgraduate research team leader, Renate Schmidt see [project contacts](contact.html#cosupervise)

## KTPs and IAAs

Alongside projects co-supervised by academics, other kinds of collaobration are also possible including Knowledge Transfer Partnerships (KTPs) and Impact Acceleration Accounts (IAAs).

### Knowledge Transfer Partnerships {#ktp}

We have a range of [KTPs](https://www.gov.uk/guidance/knowledge-transfer-partnerships-what-they-are-and-how-to-apply), speak to the research office for details


### Impact Acceleration Accounts {#iaa}

We have a range of Impact Acceleration Accounts [IAAs](https://epsrc.ukri.org/innovation/fundingforimpact/impact-acceleration-accounts/), speak to the research office for details


## Intellectual Property {#ip}

By default, students own the Intellectual Property of their work done while studying. Other arrangements for IP can be made depending on the nature of the project.